### ISSUE TITLE
Login in doesn't accept enter

### ISSUE THREAD

**Issue by sleepingchinchilla** [Tellmarch/playshogi#10]
title says it all

**Comment by ddugovic** [comment]
There was a login page?  I can't find the code for it.

**Comment by Tellmarch** [comment]
https://github.com/Tellmarch/playshogi/blob/master/playshogi-website-gwt-mvn/src/main/java/com/playshogi/website/gwt/client/ui/LoginView.java

**Comment by ddugovic** [comment]
Thanks, I see... I wonder, in light of #5 and not wanting to manage an email server, perhaps I should attempt to implement "Login with Lichess"?

https://chesscup.org/login uses a different framework but shows this is possible.

**Comment by Tellmarch** [comment]
I think I would prefer to not introduce that dependency at the moment. The database is already setup to handle authentication, only a few things are missing (password hashing, HTTPS). We can initially roll it out without email confirmation/recovery.
