### ISSUE TITLE
pawn drop mate

### ISSUE THREAD

**Issue by sleepingchinchilla** [Tellmarch/playshogi#12]
Need to add legal move condition for it.

**Comment by timezombi** [comment]
For people wanting to contribute, this already has a dummy implementation for

**Comment by timezombi** [comment]
For people wanting to contribute, this appears to still be an open bug. There is an existing dummy method called isPawnDropMate(ShogiBoardState, Square) that can be found in [PawnMovement.java](https://github.com/Tellmarch/playshogi/blob/8c1dc938d528fe5699b706d7113864d9c7d07856/playshogi-library-shogi/src/main/java/com/playshogi/library/shogi/rules/movements/PawnMovement.java). It seems like it would only have to make a call to isPositionCheckmate(ShogiPosition, boolean) from [ShogiRulesEngine.java](https://github.com/Tellmarch/playshogi/blob/8c1dc938d528fe5699b706d7113864d9c7d07856/playshogi-library-shogi/src/main/java/com/playshogi/library/shogi/rules/ShogiRulesEngine.java).

**Comment by timezombi** [comment]
Ah! I just noticed that the logic was implemented in a recent commit by Tellmarch: Tellmarch/playshogi:@ca3385a0371b3ac626bffdb09c07021eab4262d2

The logic is contained within the GameNavigator. This means that the PawnMovement's isPawnDropMate() method may be unnecessary and is a good candidate for removal during a refactor.

**Comment by ddugovic** [comment]
I am adding a JUnit test to verify the functionality.  I do not see logic contained inside GameNavigation.java.
