### ISSUE TITLE
Tsume categories (1-11 moves) doesn't work when you go skip/next

### ISSUE THREAD

**Issue by sleepingchinchilla** [Tellmarch/playshogi#21]
It gives random number of moves for the next problem.

**Comment by timezombi** [comment]
It seems that there is a pull request (#41)  made by @ddugovic that attempts to solve this problem.

**Comment by Tellmarch** [comment]
I wasn't able to reproduce this problem recently - I think it may have been fixed by https://github.com/Tellmarch/playshogi/commit/34279aec12def96d445d2c40dcf7d48591203b36, closing for now.
