### ISSUE TITLE
Even if the move is illegal, the promotion window still pops out

### ISSUE THREAD

**Issue by sleepingchinchilla** [Tellmarch/playshogi#35]
**Describe the bug**
If you click on a piece that can promote and then click on any other square, promotion window will pop out.

**To Reproduce**
1. Go to tsume problems
2. Click on any piece that can promote
3. click on any other square

**Expected behavior**
The piece becomes unselected

**Comment by ddugovic** [comment]
Additional information: https://clips.twitch.tv/SarcasticWittyBeanBIRB
