### ISSUE TITLE
Add an option to use "international" pieces

### ISSUE THREAD

**Issue by Tellmarch** [Tellmarch/playshogi#44]
The user should be able to choose between traditional pieces or Hidetchi international pieces

**Comment by timezombi** [comment]
If switching piece sets is an option, I think many people would prefer being able to use the default 1-kanji pieces on 81Dojo. I have even been trying to encourage streamers to switch their default ShogiGUI piece sets to look exactly like the 81Dojo default pieces.

Example piece set:
https://raw.githubusercontent.com/Little-Magician/ShogiGUI-piece-sets/master/PNG/1kanji%20HiRez.png
