### ISSUE TITLE
Feature Request: Ability to export the initial position from TsumeView mode in SFEN format.

### ISSUE THREAD

**Issue by timezombi** [Tellmarch/playshogi#45]
**Is your feature request related to a problem? Please describe.**
I want to be able to access the position of the initial checkmate problem as a SFEN (or KIF) file to make it easier to do things like modifying tsumeshogi problems or for easier input into Anki using the [Shogi plugin](https://github.com/tokoharu/shogi_addon_for_Anki). The whole solution available as a KIF export would also be cool, but a simple SFEN would still be a huge quality of life improvement.

**Describe the solution you'd like**
An extra button available somewhere in the TsumeView that allows you to view the SFEN and/or copy it to the clipboard. The Shogi Playground (Mog Project) website has a good example of a SFEN export in their "Share" options. 

Example screenshot of Shogi Playground's version:
https://user-images.githubusercontent.com/600562/89496541-6390d800-d76f-11ea-847f-68864e10c57d.PNG

**Comment by Tellmarch** [comment]
SFEN conversion is already implemented (see SfenConverter.toSFEN()), so this issue is only about adding the appropriate button in the UI.
