### ISSUE TITLE
Upgrade to GWT 2.9

### ISSUE THREAD

**Issue by ddugovic** [Tellmarch/playshogi#52]
**Is your feature request related to a problem? Please describe.**
Builds could be faster.  Also, when developing new features (such as kifu import) if feasible do not use deprecated technology.

**Describe the solution you'd like**
Upgrade GWT and [Elemental2](https://github.com/google/elemental2) to current versions, then re-evaluate.
https://stackoverflow.com/a/52083441

**Describe alternatives you've considered**
1. Add playshogi/playshogi-website-gwt-mvn/src/test and remove files until it can be identified why builds are slow
2. Enable parallel execution in builds, if feasible

**Additional context**
https://gist.github.com/branflake2267/d424e4a0c0b371e3dd9d15bfd3514429 is an example file reader.

**Comment by Tellmarch** [comment]
Agree that we should upgrade to GWT 2.9 (need to make sure nothing breaks first).
Regarding the kifu import, there is only a bit of (incomplete) code using elements that I wrote a few years back (at the time it was the latest technology).

However I am not sure what the impact on build speed will be (but I don't see this a problem currently - the GWT build is about 40 seconds in github actions right now, and that's the full package for production build - development is much faster in super devmode. Do you have specific concern with build speed?

**Comment by Tellmarch** [comment]
Upgraded to GWT 2.9.
