### ISSUE TITLE
Allow piece deselection

### ISSUE THREAD

**Issue by ddugovic** [Tellmarch/playshogi#66]
**Describe the bug**
To clear piece selection I need to click an invalid move.

**To Reproduce**
1. Click a piece (either on the board or piece stand) to select it,
2. Click again to attempt to deselect it.

**Expected behavior**
Piece is no longer selected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS Edge
 - Version: current

**Comment by Tellmarch** [comment]
This has been fixed some time ago
