### ISSUE TITLE
Add username validation

### ISSUE THREAD

**Issue by timezombi** [Tellmarch/playshogi#73]
There are a couple oddities that are produced from a lack of user validation when registering a new user.

![image](https://user-images.githubusercontent.com/600562/113490705-b8acf700-9480-11eb-8a94-1fda037ea526.jpeg)

1) Usernames are case sensitive.

As you can see in the above screenshot, there is an entry for both "Koshiro" and "koshiro" in the high scores table. I can imagine this would generate issues ranging from accidental account creation to zany antics involving user impersonation.

Perhaps a solution similar to what which does would be a viable alternative? The username itself must be all lowercase but the display name in the URL can have arbitrary capitalization.

2) Usernames are allowed to have special characters such as "@" in the name. 

Note that there is also a user called "@shogi.brasil" in the screenshot. Perhaps it will never be an issue, but oftentimes allowing special symbols in the username will cause unexpected behavior when attempting to parse the stream. The problem can be sidestepped by restricting the number of valid characters to create a username.

**Comment by Tellmarch** [comment]
I believe this was fixed with https://github.com/Tellmarch/playshogi/commit/ca2943c6c055fa4b7e79faec21675725bf746b30 and https://github.com/Tellmarch/playshogi/commit/ca121348b7f7adcdf580a0deea45e0eda80e2b11
